import "@/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

import { Sidebar } from "@/app/_components/Sidebar";
import { TRPCReactProvider } from "@/trpc/react";

export const metadata: Metadata = {
  title: "Pokédex Alberto",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="es" className={`${geist.variable}`}>
      <body>
        <TRPCReactProvider>
          <div className="min-h-screen flex bg-gradient-to-b from-[#2e026d] to-[#15162c] text-white">
            <Sidebar />
            <main className="flex-1 flex flex-col h-screen overflow-y-auto">{children}</main>
          </div>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
